[@ww.textfield labelKey="bamboo-opsworks.stack_name" name="stack_name" required="true"/]
[@ww.textfield labelKey="bamboo-opsworks.app_name" name="app_name" required="true"/]
[@ww.textfield labelKey="bamboo-opsworks.profile" name="profile"/]
[@ww.textfield labelKey="bamboo-opsworks.access_key_id" name="access_key_id"/]
[@ww.textfield labelKey="bamboo-opsworks.secret_access_key" name="secret_access_key"/]
