[@ww.label labelKey="bamboo-opsworks.stack_name" name="stack_name"/]
[@ww.label labelKey="bamboo-opsworks.app_name" name="app_name"/]
[@ww.label labelKey="bamboo-opsworks.profile" name="profile"/]
[@ww.label labelKey="bamboo-opsworks.access_key_id" name="access_key_id"/]
[@ww.label labelKey="bamboo-opsworks.secret_access_key" name="secret_access_key" value="********"/]
